version: "1"

services:
  mssql-db:
    container_name: vetmasters-db
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test@123
      - MSSQL_DB=vetmasters
